### ISSUE TITLE
Write algorithms in C

### ISSUE THREAD

**Issue by Tib-ved** [Tib-ved/Algorithms#1]

**Comment by zilehuda** [comment]
give description about issue ?

**Comment by debodirno** [comment]
@Tib-ved which algorithms are you talking about? If any algorithm in general, I'm up for it.

**Comment by Tib-ved** [comment]
Can you write an algo to print the power of any number without using pow
function ???

Do mind here both the base and the exponent are float (fraction).

Regards
Ved
