### ISSUE TITLE
Write Algorithms in C

### ISSUE THREAD

**Issue by Tib-ved** [Tib-ved/Algorithms#2]
Try practicing algorithms in C

1. Create a folder with your user name in folder C.
2. Write all the algorithms in the following folder.

**Comment by StanSinai1** [comment]
Hello,
Can I write some algorithms for you in C?

**Comment by upinderawat** [comment]
Hi, I would really appreciate if you could let me implement algorithms in C.

**Comment by Tib-ved** [comment]
@StanSinai1 Please go ahead !

**Comment by Tib-ved** [comment]
@upizzz Sure send me a PR.

**Comment by isqwen** [comment]
Hi ,can I take this?
